module.exports = {
  content: ['./src/renderer/**/*.{js,jsx,ts,tsx}', './assets/index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'accent': 'var(--color-accent)',
        'icon-tile': 'var(--color-icon-tile)',
        'on-icon-tile': 'var(--color-on-icon-tile)',
        'success': 'var(--color-success)',
        'on-success': 'var(--color-on-success)',
        'info': 'var(--color-info)',
        'on-info': 'var(--color-on-info)',
        'online': 'var(--color-online)',
        'offline': 'var(--color-offline)',
        'primary': 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'secondary': 'var(--color-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'surface': 'var(--color-surface)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'progress-track': 'var(--color-progress-track)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-background': 'var(--color-on-background)',
        'background': 'var(--color-background)',
        'outline': 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'error': 'var(--color-error)',
        'error-container': 'var(--color-error-container)',
        'error-container-hover': 'var(--color-error-container-hover)',
        'on-error-container': 'var(--color-on-error-container)',
        'warning': 'var(--color-warning)',
        'on-warning': 'var(--color-on-warning)',
        'primary-hover': 'var(--color-primary-hover)',
        'surface-control': 'var(--color-surface-control)',
        'surface-control-hover': 'var(--color-surface-control-hover)',
        'warning-container': 'var(--color-warning-container)',
        'on-warning-container': 'var(--color-on-warning-container)',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
    },
  },
}
