// Generated from events.js. A literal union, not `string`: subscribe() takes an EventName, so a
// mistyped name fails tsc instead of silently never firing. The union must equal EVENT_NAMES
// exactly — contract-declarations.test.js asserts it, the same way it does for RequestName.
export type EventName =
  | 'event:audit-updated'
  | 'event:awareness'
  | 'event:decoration'
  | 'event:download-roots-status'
  | 'event:files-updated'
  | 'event:foreign-folder-mount-status'
  | 'event:foreign-folder-preview-progress'
  | 'event:join-requests-updated'
  | 'event:leave-progress'
  | 'event:member-avatar-updated'
  | 'event:member-join-request'
  | 'event:member-joined'
  | 'event:member-left'
  | 'event:members-updated'
  | 'event:membership-creator-divergence'
  | 'event:membership-denied'
  | 'event:membership-granted'
  | 'event:mirrors-updated'
  | 'event:network-status'
  | 'event:owned-folder-index-progress'
  | 'event:owned-folder-mount-status'
  | 'event:owned-folder-preview-progress'
  | 'event:owned-folder-scan-completed'
  | 'event:profile-needed'
  | 'event:reconcile'
  | 'event:share-files-updated'
  | 'event:share-index-progress'
  | 'event:shares-updated'
  | 'event:state'
  | 'event:transfer-complete'
  | 'event:transfer-error'
  | 'event:transfer-paused'
  | 'event:transfer-removed'
  | 'event:transfer-superseded'
  | 'event:worker-ready'

export declare const EVENT_NAMES: readonly EventName[]
