// Every event the worker pushes to the renderer. Emitted names are the source of truth: this list
// is generated from them, and the taxonomy test fails if an emit site appears that is not here.
export const EVENTS = Object.freeze({
  AUDIT_UPDATED: 'event:audit-updated',
  AWARENESS: 'event:awareness',
  DECORATION: 'event:decoration',
  DOWNLOAD_ROOTS_STATUS: 'event:download-roots-status',
  FILES_UPDATED: 'event:files-updated',
  FOREIGN_FOLDER_MOUNT_STATUS: 'event:foreign-folder-mount-status',
  FOREIGN_FOLDER_PREVIEW_PROGRESS: 'event:foreign-folder-preview-progress',
  JOIN_REQUESTS_UPDATED: 'event:join-requests-updated',
  LEAVE_PROGRESS: 'event:leave-progress',
  MEMBER_AVATAR_UPDATED: 'event:member-avatar-updated',
  MEMBER_JOIN_REQUEST: 'event:member-join-request',
  MEMBER_JOINED: 'event:member-joined',
  MEMBER_LEFT: 'event:member-left',
  MEMBERS_UPDATED: 'event:members-updated',
  MEMBERSHIP_CREATOR_DIVERGENCE: 'event:membership-creator-divergence',
  MEMBERSHIP_DENIED: 'event:membership-denied',
  MEMBERSHIP_GRANTED: 'event:membership-granted',
  MIRRORS_UPDATED: 'event:mirrors-updated',
  NETWORK_STATUS: 'event:network-status',
  OWNED_FOLDER_INDEX_PROGRESS: 'event:owned-folder-index-progress',
  OWNED_FOLDER_MOUNT_STATUS: 'event:owned-folder-mount-status',
  OWNED_FOLDER_PREVIEW_PROGRESS: 'event:owned-folder-preview-progress',
  SHARE_INDEX_PROGRESS: 'event:share-index-progress',
  OWNED_FOLDER_SCAN_COMPLETED: 'event:owned-folder-scan-completed',
  PROFILE_NEEDED: 'event:profile-needed',
  SHARE_FILES_UPDATED: 'event:share-files-updated',
  SHARES_UPDATED: 'event:shares-updated',
  STATE: 'event:state',
  TRANSFER_COMPLETE: 'event:transfer-complete',
  TRANSFER_ERROR: 'event:transfer-error',
  TRANSFER_PAUSED: 'event:transfer-paused',
  TRANSFER_REMOVED: 'event:transfer-removed',
  TRANSFER_SUPERSEDED: 'event:transfer-superseded',
  WORKER_READY: 'event:worker-ready',
})

export const EVENT_NAMES = Object.freeze(Object.values(EVENTS))
