// Generated from requests.js. A literal union, not `string`: REQUESTS declared as
// Record<string, RequestSpec> makes `keyof` useless — request('spces:list') would compile, which
// is how a handler name escaped the contract once already. Same lesson as the status tuples.
export type RequestName =
  | 'audit:actors'
  | 'audit:configure'
  | 'audit:export'
  | 'audit:get-config'
  | 'audit:list'
  | 'audit:purge'
  | 'audit:spaces'
  | 'audit:stats'
  | 'diagnostics:export'
  | 'downloads:roots-status'
  | 'event:loose-file-fs-event'
  | 'event:owned-folder-fs-event'
  | 'features:get'
  | 'feedback:send'
  | 'files:add'
  | 'files:cancel-download'
  | 'files:cancel-publish'
  | 'files:discard-partial'
  | 'files:download'
  | 'files:list'
  | 'files:pause-download'
  | 'files:remove'
  | 'files:reveal'
  | 'foreign-folder:cancel-preview'
  | 'foreign-folder:get'
  | 'foreign-folder:list-all'
  | 'foreign-folder:mount'
  | 'foreign-folder:preview'
  | 'foreign-folder:set-enabled'
  | 'foreign-folder:relocate'
  | 'foreign-folder:unmount'
  | 'foreign-folder:validate'
  | 'members:online'
  | 'mounts:list-all'
  | 'network:check-liveness'
  | 'network:online-hint'
  | 'network:probe-canary'
  | 'network:reconnect'
  | 'network:set-relays'
  | 'network:status:get'
  | 'network:test-relay'
  | 'owned-folder:cancel-preview'
  | 'owned-folder:delete'
  | 'owned-folder:get'
  | 'owned-folder:index-status'
  | 'owned-folder:list-all'
  | 'owned-folder:mount'
  | 'owned-folder:pause-index'
  | 'owned-folder:preview'
  | 'owned-folder:relocate'
  | 'owned-folder:resume-index'
  | 'owned-folder:validate'
  | 'ping'
  | 'profile:get'
  | 'profile:set'
  | 'serving:detail-subscribe'
  | 'serving:detail-unsubscribe'
  | 'serving:summary-list'
  | 'setVerbose'
  | 'settings:set-bandwidth'
  | 'settings:set-download-folder'
  | 'share:create'
  | 'share:delete'
  | 'share:rename'
  | 'share:discard-partial'
  | 'share:folder-info'
  | 'share:list'
  | 'share:list-files'
  | 'share:read-file'
  | 'share:reveal-file'
  | 'share:reveal-folder'
  | 'shutdown'
  | 'space:approve-member'
  | 'space:create'
  | 'space:deny-member'
  | 'space:invite'
  | 'space:join'
  | 'space:leave'
  | 'space:members'
  | 'space:mirrors'
  | 'space:pending-requests'
  | 'space:storage-summary'
  | 'space:toggle-favorite'
  | 'space:update'
  | 'spaces:list'
  | 'storage:info'

export type ArgType = 'string' | 'number' | 'boolean' | 'array' | 'spaceId' | 'shareId' | 'path'
export interface ArgRule { type: ArgType; optional?: boolean; max?: number }
export interface RequestSpec { kind: 'query' | 'command'; args: Record<string, ArgRule>; fails?: readonly string[]; cancellable?: boolean }
export declare const ARG: Readonly<Record<ArgType, ArgType>>
export declare const REQUESTS: Readonly<Record<RequestName, RequestSpec>>
export declare const REQUEST_NAMES: readonly RequestName[]
export declare const UNREFERENCED_REQUESTS: readonly RequestName[]
