// UI vocabulary the model layer names in its own return types. It lives here so a derivation does
// not have to import a component or a hook to describe what it returns.

export type IconName =
  | 'add_circle'
  | 'architecture'
  | 'arrow_back'
  | 'arrow_forward'
  | 'article'
  | 'auto_awesome'
  | 'bar_chart'
  | 'check'
  | 'check_circle'
  | 'chevron_right'
  | 'close'
  | 'cloud'
  | 'code'
  | 'computer'
  | 'content_copy'
  | 'dark_mode'
  | 'data_object'
  | 'database'
  | 'delete'
  | 'description'
  | 'desktop_windows'
  | 'download'
  | 'draft'
  | 'edit'
  | 'edit_note'
  | 'error'
  | 'expand_more'
  | 'feedback'
  | 'folder'
  | 'folder_download'
  | 'folder_open'
  | 'folder_zip'
  | 'group'
  | 'group_add'
  | 'history'
  | 'hub'
  | 'image'
  | 'info'
  | 'keyboard'
  | 'keyboard_arrow_down'
  | 'light_mode'
  | 'lock'
  | 'logout'
  | 'menu_book'
  | 'more_vert'
  | 'movie'
  | 'music_note'
  | 'notifications'
  | 'open_in_new'
  | 'palette'
  | 'pause'
  | 'photo_camera'
  | 'picture_as_pdf'
  | 'play_arrow'
  | 'refresh'
  | 'school'
  | 'science'
  | 'search'
  | 'send'
  | 'settings'
  | 'shield'
  | 'star'
  | 'stop'
  | 'table_chart'
  | 'tips_and_updates'
  | 'tune'
  | 'update'
  | 'verified_user'
  | 'visibility'
  | 'visibility_off'
  | 'warning'
  | 'work'

export type DecorationPhase = 'verifying' | 'preparing' | 'publishing'

export interface Decoration {
  bytes: number
  total: number
  speed: number
  avgSpeed: number
  eta: number | null
  phase?: DecorationPhase
  verifyFraction?: number
}
